version: "3"

vars:
  USERNAME:
    sh: whoami
  HOME_DIR: /Users/{{.USERNAME}}
  HOSTNAME:
    sh: scutil --get ComputerName 2>/dev/null || uname -n
  OS:
    sh: uname -s

tasks:
  default:
    cmds:
      - task --list

  build-config:
    internal: true
    cmds:
      - |
        if [ "{{.OS}}" = "Darwin" ]; then
          nix build .#darwinConfigurations.{{.HOSTNAME}}.system --impure --show-trace
        else
          nix build .#homeConfigurations.linux.activationPackage --impure --show-trace
        fi

  switch-config:
    internal: true
    cmds:
      - |
        if [ "{{.OS}}" = "Darwin" ]; then
          darwin-rebuild switch --flake .#{{.HOSTNAME}} --impure --show-trace
        else
          ./result/activate
        fi

  update:
    cmds:
      - nix flake update
    desc: Update the flake.lock file

  update-mailerlite:
    cmds:
      - nix flake lock --update-input mailerlite
    desc: Update the mailerlite input in the flake.lock file

  build:
    deps: [build-config, switch-config]
    desc: Build and apply the new configuration based on the OS

  update-build:
    deps: [update, build]
    desc: Update the flake.lock file and build the new configuration
