{ config
, lib
, pkgs
, hostConfig
, ...
}:

let
  inherit (lib) mkIf;
  cfg = hostConfig.ssh or { };
in
{
  config = mkIf (cfg.enable or false) {
    home.file.".ssh/config".text = ''
      # Basic SSH Configuration
      # Generated by nix-config - DO NOT EDIT MANUALLY

      ${lib.optionalString (cfg.includeOrbstack or true) ''
      Include ~/.orbstack/ssh/config
      ''}

      Host *
        AddKeysToAgent yes
        User ${hostConfig.username}
        UseKeyChain yes
        StrictHostKeyChecking=no
        ${lib.optionalString (cfg.use1PasswordAgent or true) ''
        IdentityAgent "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
        ''}

      ${cfg.extraConfig or ""}
    '';

    # Make sure the .ssh directory exists with correct permissions
    home.activation.ensureSshDirectory = lib.hm.dag.entryBefore [ "writeBoundary" ] ''
      $DRY_RUN_CMD mkdir -p $VERBOSE_ARG ~/.ssh
      $DRY_RUN_CMD chmod 700 $VERBOSE_ARG ~/.ssh
    '';
  };
}
