{ ... }:
{
  flake.modules.homeManager.ssh = { config, lib, ... }:
    let
      cfg = config.meta.ssh;
    in
    lib.mkIf cfg.enable {
      home.file.".ssh/config".text = ''
        # Basic SSH Configuration
        # Generated by nix-config - DO NOT EDIT MANUALLY

        ${lib.optionalString cfg.includeOrbstack ''
          Include ~/.orbstack/ssh/config
        ''}

        Host *
          AddKeysToAgent yes
          User ${cfg.username}
          UseKeychain yes
          ${lib.optionalString cfg.use1PasswordAgent ''
            IdentityAgent "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
          ''}

        ${cfg.extraConfig}
      '';

      home.activation.ensureSshDirectory = lib.hm.dag.entryBefore [ "writeBoundary" ] ''
        $DRY_RUN_CMD mkdir -p $VERBOSE_ARG ~/.ssh
        $DRY_RUN_CMD chmod 700 $VERBOSE_ARG ~/.ssh
      '';
    };
}
